---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "demo-mlflow-agent-tracing-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demo-mlflow-agent-tracing"
  template:
    metadata:
      labels:
        app: "demo-mlflow-agent-tracing"
    spec:
      containers:
        - name: "demo-mlflow-agent-tracing"
          image: "quay.io/rh_ee_taagarwa/demo_mlflow_agent_tracing:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: demo-mlflow-agent-tracing-secret  
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
      restartPolicy: Always
  strategy:
    type: RollingUpdate
