apiVersion: v1
kind: Secret
metadata:
  name: demo-mlflow-agent-tracing-secret
data:
  OPENAI_API_KEY: 
  OPENAI_MODEL_NAME: 
  OPENAI_BASE_URL: 
  CHAINLIT_AUTH_SECRET: 
  MLFLOW_TRACKING_URI: 
  MLFLOW_EXPERIMENT_NAME: 
  MLFLOW_ACTIVE_MODEL_ID: 
type: Opaque